# Generated by Django 3.1.6 on 2021-02-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210224_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
