# Generated by Django 3.1.6 on 2021-02-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_watchedmovies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchedmovies',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='watchedmovies',
            old_name='user_id',
            new_name='user',
        ),
    ]
