# Generated by Django 3.1.7 on 2021-03-08 14:01

from django.db import migrations
import easy_thumbnails.fields
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20210303_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=movie.models.upload_path),
        ),
    ]
