# Generated by Django 3.1.7 on 2021-03-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20210308_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeDislikeOption',
        ),
    ]
